### ISSUE TITLE
Replace the default app icon with the SaferMobile lock PNG

### ISSUE THREAD

**Issue by n8fr8** [SaferMobile/InTheClear#11]
right now the default Android ITC app icon is the Setup gear, needs to be switched to the SaferMobile lock as a transparenty PNG

**Comment by djhalliday** [comment]
we still want the Setup icon to be the gear, right? where does the default Android ITC app icon show up, in this case?

_update_ duh! in places like Settings > Applications" or other application list views

**Comment by n8fr8** [comment]
I don't think we need a seperate setup icon or app. We just want:

1) InTheClear: the main app for settings, wizard, etc
2) Wipe: direct data wipe access
3) Shout: direct shout access
4) Panic! the one touch panic button

I think we need some way for these icons to all show up near each other,
or have a unifying motif... the little ITC lock perhaps on each?

We may also want to name the apps: ITC Panic! ITC Shout! ITC Wipe, so
they all end up in the same place in the launcher

**Comment by djhalliday** [comment]
time for another rebranding session! :D
