### ISSUE TITLE
Panic, Wipe and Shout all need spinning progress dialogs showing progress

### ISSUE THREAD

**Issue by n8fr8** [SaferMobile/InTheClear#14]
we can talk more about this, but we do want to indicate that something is happening, especially during what could be a long delay in the Wipe portion of Panic

**Comment by djhalliday** [comment]
we need to discuss how this conflicts with #47 - namely that for activists, it's in their best interests to have this happen completely in the background, with no notifications whatsoever. especially if the process takes a while.

**Comment by n8fr8** [comment]
for now on the Java/Blackberry, this happens in the foreground, as running apps as background services is not really supported that well

**Comment by n8fr8** [comment]
This is closed. We have implemented background wipe on Android. On Java/BB phones you can exit the app and it will continue to run if the device supports that, otherwise the foreground UI dialog display will show.
