### ISSUE TITLE
CallLog wiping crashes on Android 2.3.3 / Nexus One

### ISSUE THREAD

**Issue by n8fr8** [SaferMobile/InTheClear#15]
I get a FC when trying to wipe call log data. The log output is:

Android contentprovider java.lang.UnsupportedOperationException: Cannot delete that URL:  content://call_log/calls/442 

It may be this specific call itself that is causing the problem?

Seems like some device don't allow you to delete call logs at all, so we should handle that as well.

**Comment by n8fr8** [comment]
this code doesn't seem completely right, but it does show another query oriented approach that might work:

  public void clearCallLog() { 
                Cursor c = 
getContentResolver().query(Calls.CONTENT_URI, null, 
                                Calls.NUMBER + "='" + mobileNumber + 
"'", null, 
                                Calls.DATE + " DESC"); 
                getContentResolver().cancelSync(Calls.CONTENT_URI); 
                startManagingCursor(c); 
                String number = null; 
                String date; 
                int dateColumn = c.getColumnIndex(Calls.DATE); 
                int numberColumn = c.getColumnIndex(Calls.NUMBER); 
                if (c != null) { 
                        if (c.moveToFirst()) { 
                                // do { 
                                // Get the field values 
                                date = c.getString(dateColumn); 
                                number = c.getString(numberColumn); 
                                Log.d("NUmber", number); 
                                Log.d("Date", date); 
                                alert("number", number); 
                                // } while (c.moveToNext()); 
                        } 
                        int i 
=getContentResolver().delete(Calls.CONTENT_URI, 
                                        Calls.NUMBER + "='" + number + 
"'", null); 
                        alert("Delete", Integer.toString(i)); 
                } 
        } 

from here: http://groups.google.com/group/android-developers/browse_thread/thread/eebcb40ea32093a2

**Comment by harlo** [comment]
OK!!!!!!!!!!!!
