### ISSUE TITLE
Checkboxes not working on Wizard Flow: Nokia 2700

### ISSUE THREAD

**Issue by djhalliday** [SaferMobile/InTheClear#24]
One of our bigger issues for usability testing scheduled for 4-August. If possible, should push a fix and test on local 2700 hardware immediately.

**Comment by djhalliday** [comment]
green 'place call' button appears to be mapped to this functionality incorrectly.

**Comment by n8fr8** [comment]
This is a known problem with some nokia devices. working on it now
