### ISSUE TITLE
wizardStatusTrack is not drawn to be density-independent

### ISSUE THREAD

**Issue by djhalliday** [SaferMobile/InTheClear#28]
Testing on alternate screen sizes causes major issues for this. Needs to be draw density-independently. One good thread I found on this: 

http://stackoverflow.com/questions/4183372/how-to-properly-scale-a-game-on-android

**Comment by harlo** [comment]
I think you nixxed this one, @djhalliday.

**Comment by djhalliday** [comment]
Nah, I tried to make it fit correctly for a nexus one but found that draw() only works for actual pixels so unfortunately it's still open. Try checking it out on a smaller screen size in emulator and those circles are huge!
