### ISSUE TITLE
Data Wipe selection box first item titled 'Edit'

### ISSUE THREAD

**Issue by djhalliday** [SaferMobile/InTheClear#35]
Looks like we're re-using the selection dialog from the wizard in this view - which is good - however one aspect of the dialog that was lost in translation is the string for the first option. In the wizard it is correctly labeled as 'None' -- however when accessed from the Data Wipe screen it is labeled as 'Edit'

**Comment by harlo** [comment]
Solved in [this commit](https://github.com/SaferMobile/InTheClear/commit/c31273f315b18d816268eef10f416f9c399a3a65)
