### ISSUE TITLE
Testing Emergency SMS Always reports success!

### ISSUE THREAD

**Issue by djhalliday** [SaferMobile/InTheClear#36]
Wizard Screen #2 - 

Just tested using a fake, 9 digit number and the app reported success immediately. Something fishy going on here...

**Comment by harlo** [comment]
Kind of: android will attempt any input as long as it's not null/blank.  I
suppose it could use a number validation method?  In which case, different
regions could require different validation methods (which actually seem
do-able if we base it off of the user's country code...)

**Comment by djhalliday** [comment]
is there any way that we can confirm that the device actually _sent_ an SMS successfully? i.e. beyond form validation, some way to know that it was accepted by the messaging app (or whatever)...

**Comment by harlo** [comment]
yes you can!  i made some progress on this over the weekend: the sms manager will send a result code on a successful send.  currently working on implementing this in the SMSSender class in a way that's reusable in whatever context the app requires...

**Comment by harlo** [comment]
ok, fixed.

**Comment by djhalliday** [comment]
seeing some string mixups on my local build (i.e. button title now 'SMS Test Failure'). maybe something weird on my end?

**Comment by harlo** [comment]
weird.  that has happened to me before, though.  i don't have any fixes,
though.

**Comment by harlo** [comment]
you might try regenerating R? ultimately, the strings could use some
cleaning up eventually (but this will be another issue).

**Comment by djhalliday** [comment]
i think that's exactly what it was. all good!
