### ISSUE TITLE
first digit of phone numbers entered into the test SMS does not enter properly

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#37]
I'm in the screen to test the Emergency SMS and enter a number in the box after "The first step is to send a test SMS" -- I begin typing my number into the box and the first number does not enter; have to type it again

**Comment by djhalliday** [comment]
this sounds like a system lag issue with j2me based on my own experience. it's because it has to transition to the fullscreen text entry format. not sure what we can do about it. prioritizing as a 'nice to have'

**Comment by n8fr8** [comment]
fixed... it was a bug in the low level UI library we are using. should work now. first letter you type will open the entry box, and the value should be there.
