### ISSUE TITLE
Responsiveness of 'next' buttons in the Setup wizard

### ISSUE THREAD

**Issue by katrinskaya** [SaferMobile/InTheClear#46]
Buttons not very responsive to touch on screen - can only activate via scroll.

**Comment by katrinskaya** [comment]
Actually, it's all buttons, not just the next button.  Can not, for instance, activate the specific wipe features.

**Comment by katrinskaya** [comment]
Phone model is G2, by the way - Cyanmod, latest build.

**Comment by djhalliday** [comment]
tried to reproduce on G2. this looks like it may have been an underlying system issue with available memory. Until we can reproduce with a log or it is regularly reproducible, I am lowering the priority for now.
