### ISSUE TITLE
Putting wipe and send into background?

### ISSUE THREAD

**Issue by katrinskaya** [SaferMobile/InTheClear#47]
Should we have the wipe/send feature running in the background rather than on a black screen?  This is VERY obvious should someone have a hold of the phone...

**Comment by djhalliday** [comment]
Yes, this should be changed for all platforms. @bxhz also filed this on android specifically (ref: #50), which I will close. Escalating this to a 'Must Have' as I feel it's that important.

**Comment by djhalliday** [comment]
assigning this to @n8fr8, but @harlo should also be aware.

**Comment by n8fr8** [comment]
you can't force Java apps to run in the background. the user can leave the app by pressing home, but that doesn't necessarily mean it will keep running. 

so, for Java/Nokia and Blackberry, this is a NICE TO HAVE. I think for a future release, we could redesign the panic screen such that it looks like nothing, rather than what it shows now.

For Android, it is definitely possible.

**Comment by djhalliday** [comment]
OK, thanks! changing this ticket to apply to Android only and assigning to @harlo. #14 represents the desired (and current) functionality for J2ME and BB.

**Comment by katrinskaya** [comment]
Get your butt into the park :)

------Original Message------

**Comment by harlo** [comment]
:(

in work mode!!!  i suck, i know!

**Comment by katrinskaya** [comment]
Don't ship a thing. Stop bug fixing. Gorgeous weather! Food!!!!! We are not releasing until late next week!!! 

------Original Message------

**Comment by harlo** [comment]
Implemented in Shout.  Wipe coming next...

**Comment by harlo** [comment]
Ok, wipe is now running in the background, so UI doesn't hang no matter how long wipe takes to execute.  Still not sure where we stand on notifications: will user see progress bar (maybe in notifications tray?) or will the app do its thing in the background without letting the user know.  (Maybe we want a toast or something confirming complete wipe?)

Let me know, and I'll update the UI accordingly.  Closing this ticket for now, but we can revisit it for UI fixes.

**Comment by djhalliday** [comment]
great! will test. i think toasts are a good method of notification for this - at least for now. maybe for 0.4 we can get snazzier.
