### ISSUE TITLE
Crashes in G2 Datawipe

### ISSUE THREAD

**Issue by katrinskaya** [SaferMobile/InTheClear#48]
Data wipe crashes - error: Activity Wipe! in application InTheClear is not responding.

**Comment by djhalliday** [comment]
At a minimum, this requires a progress dialog to be shown on wipe activation (ref #14).

G2 force closes regularly on wipe of everything. See pastebin: http://pastebin.com/7Y0rPwKk

**Comment by harlo** [comment]
Wipe now on a thread so there should be no more UI hanging/crashing.  Please test, though, and let me know how notification should be handled in UI.
