### ISSUE TITLE
All SMS messages dialogue box showing; seems to be hanging

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#54]
I set In The Clear to wipe all of my SMS and Call logs; the dialogue message "All SMS Messages/Cancel" has been showing on my screen since I activated via Panic -- it seems to be hanging.  I am sending messages  to myself using Emergency SMS; could this be the reason that this process is hanging?  Because I've been sending and receiving messages and am trying to delete them simultaneously?  I'm receiving messages fine.

**Comment by djhalliday** [comment]
ran through this with @bxhz and it looks like the feature is completing correctly -- i.e. sms messages and call logs are being wiped properly. however, the confirmation dialog box that communicates this to the user once all sms messages are deleted is hanging. what is displayed is a single line stating "All SMS Messages" with the only button available being "Cancel"

All your SMS Messages are belong to us!

**Comment by harlo** [comment]
This is now fixed.
