### ISSUE TITLE
Emergency SMS - not able to reassign number

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#55]
I'm running In The Clear on my android, HTC.  I was trying to send an Emergency SMS, so opened In The Clear nad then "Emergency SMS" -- i typed in my phone number and tried to send -- Derek received the message.  When I had first set up In The Clear, I had used his number.

We looked in the wizard, and his number is still in the EMERGENCY SMS SETUP window.

**Comment by harlo** [comment]
this is now fixed.  NOTE: the preferences are saved after the user sends their shout.  so, just opening up shout, and editing recipients _without_ sending it off will not effect their preferences.  Let me know if this isn't an optimal configuration and i'll change it...
