### ISSUE TITLE
Emergency SMS - # and message reassignment cannot highlight existing data

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#66]
using ANDROID - htc

I am in the wizard, i cannot enter a cursor and edit the recipient # or the message; i can select the box and start typing which automatically deletes the number or message.  I think it would b emore clear if i could edit the data.

**Comment by harlo** [comment]
was unable to replicate the problem on Nexus One or T-Mobile MyTouch.  what HTC model are you using?

might be a default in that particular phone's handling of edit view widgets.  will investigate...

Derek, Nathan, HC, any thoughts?

**Comment by harlo** [comment]
Ok, I see the problem:

So, when you use the wizard, the data stored in preferences are automatically populated into the fields.  What you see as non-editable text is actually "Hint Text" (autofilled text that is not actually editable like regular strings are.)

To solve it, I implemented an "OnFocusChangeListener" that populates the text field with the user's preference data as Text when user taps the edit view.  Closed in [this commit](https://github.com/SaferMobile/InTheClear/commit/c0030c54f8f9c362e9c12e5de6ce76b2069e446f).
