### ISSUE TITLE
Emergency SMS Setup - label on Recipient Mobile

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#67]
the label in the Emergency SMS setup screen says "Recipient Mobile #(s)" but should just be "Recipient Mobile #" because we are only sending to one number

**Comment by djhalliday** [comment]
android _can_ send to multiple - the limitation to one only currently exists for J2ME. do we think we want to limit Android functionality in favor of consistency?

**Comment by harlo** [comment]
I think we want to keep the comma-separated list of contacts.  Closing for now, but let me know if we make a change.
