### ISSUE TITLE
language incorrect One-Touch Panic setup option

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#69]
Using: Android, HTC

The language next to the box to cancel confirmation of action says:

"When One-Touch Panic is activated, confirm before running" 

but it should say:

"When I activate One-Touch Panic, DO NOT prompt me to confirm before running" or something similar; the language describes the opposite of this option.

**Comment by djhalliday** [comment]
good point - so to summarize the changes we need:
- checkbox should be _unchecked_ by default
- language to should change to reflect the above

**Comment by harlo** [comment]
Closed in [this commit](https://github.com/SaferMobile/InTheClear/commit/60a6ddb8050ba3fbcba8dbe9d5f7cea622adb553)
