### ISSUE TITLE
Panic hangs 

### ISSUE THREAD

**Issue by bxhghz** [SaferMobile/InTheClear#70]
I activated panic and see a dialogue box counting down and then sending an SMS; now I see a dialogue box that says "Your phone will and a button "Cancel Panic"" -- it is staying on my screen

Android HTC

**Comment by harlo** [comment]
due to the modifications made to the PIM wiper class yesterday and today,
panic is not functionning 100% yet. it will be back in working order by
tomorrow.
On Aug 16, 2011 3:08 PM, "bxhz" <
reply@reply.github.com>
wrote:

**Comment by djhalliday** [comment]
cool, thanks @harlo. assume this is the same bug that's responsible for the FC on panic that I'm seeing on the latest version?

**Comment by harlo** [comment]
Yes, I believe so.  My last commit should solve the crash.
