### ISSUE TITLE
Panic Screen needs to be scrollable

### ISSUE THREAD

**Issue by djhalliday** [SaferMobile/InTheClear#71]
The section for 'data to be wiped' falls beneath the fold of the screen and is hard to view. It also makes it very difficult to scroll through those options. The whole layout should just be made scrollable to work around this.

**Comment by harlo** [comment]
Finally solved [here](https://github.com/SaferMobile/InTheClear/commit/9a90b20bd45834443527860fe6574c32db08f695)!
