### ISSUE TITLE
Panic! FC's on Samsung Galaxy Ace (2.3.4)

### ISSUE THREAD

**Issue by djhalliday** [SaferMobile/InTheClear#80]
Reference logcat: http://pastebin.com/PEZUNMiD

**Comment by n8fr8** [comment]
I had an FC with Panic, but it was b/c I had no phone number setup.

**Comment by djhalliday** [comment]
ah, that's it! should probably fix to fail gracefully in this case, but definitely not the most common of cases.

**Comment by harlo** [comment]
Investigating whatever at line 54 in shout controller is not up to code;
null is being thrown on TelephonyManager.getIMS()I.  I guess this is a
perfect opportunity to learn how different carriers/handsets provide access
to that API.

Other than handling the NPE, any tips about that model?

Thanks,
Harlo

**Comment by harlo** [comment]
possible NPEs handled in [this commit](https://github.com/SaferMobile/InTheClear/commit/893a5088fa7433ec31280453e2d50117ef24de8b).  Have read that Samsung makes IMSI unavailable, but waiting for more corroboration there...

**Comment by n8fr8** [comment]
that is good to look into, but I also think Panic needs to handle if the user has somehow skipped the setup wizard, and not manually entered a number.

**Comment by harlo** [comment]
gotcha. will update once that's implemented.
On Sep 22, 2011 6:59 PM, "n8fr8" <
reply@reply.github.com>
wrote:

**Comment by harlo** [comment]
Ok, implemented in lastest billion commits from me.  As I was doing it, I caught a critical bug in the Panic Controller that prevented it from iterating the panic message.  I would strongly recommend updating the apk and reposting it.

**Comment by harlo** [comment]
**clarification: the bug prevented user from controlling when to start/stop the panic.
