### ISSUE TITLE
Nokia 3120c: can't install zip, 'file format not supported'

### ISSUE THREAD

**Issue by mloudon** [SaferMobile/InTheClear#84]
I can't install from the zip, either off the website (download silently fails in both opera mini and default nokia browser) or by bluetoothing to the phone. If I unzip and bluetooth the jar+jad to the phone, it works (and is awesome!)

**Comment by n8fr8** [comment]
The Zip file is meant for downloading to a computer, not directly download to a device.

If you can download to a device directly, then you should just go to http://safermobile.org or the Nokia OVI store.

**Comment by mloudon** [comment]
Ah, ok. The mobile version of safermobile.org/intheclear has a link to the zip with the text 'Install Java App', can this be changed to link to the jad?

**Comment by n8fr8** [comment]
the "Install java app" code links to the JAD file.

<p> 
For Java/J2ME MIDP 2.0 Phones (Nokia, Sony Ericcson, etc)
 <a href="https://lab.safermobile.org/intheclear/app" data-role="button">Install Java App</a> 
</p> 


so something else must be happening.

**Comment by n8fr8** [comment]
Just reviewing this one last time. The language on the wiki was VERY unclear about the "offline" install process. Have improved it a bit. Thanks for the help!

Offline Install instructions:
If you want to install the application by first downloading to your desktop or laptop, then transferring the files via USB, Memory Card or Bluetooth, follow the instructions below.
For installing to Nokia/Java phones: download the InTheClear install file here: https://github.com/downloads/SaferMobile/InTheClear/InTheClear-J2ME-Signed-DesktopInstall-0.4.26.zip. This zip includes a JAD (descriptor) and JAR (the binary) that can be installed on a Nokia phone via mounting the external memory with a USB cable, through copying directly onto a micro SD card root directory, or via Bluetooth. You can then find/use the app through the applications menu, and navigate to external storage or "memory card".
For installation to an Android device: download the InTheClear application file here: https://lab.safermobile.org/intheclear/app/InTheClear-latest.apk. Copy this APK file onto your memory card and install using the Apps Installer (available on the Android Market if it is not already on your mobile).
